runtime: nodejs18
handlers:
  - url: /sw\.js
    static_files: sw.js
    upload: public/service-worker\.js
    expiration: 0m

env_variables:
  NEXT_PUBLIC_GOOGLE_ANALYTICS: ""
  NEXT_PUBLIC_BASE_URL: ""
