name: Pipeline
on:
  push:
    branches:
      - main
jobs:
  verify-code:
    name: Verify & Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: 16
      - name: npm install
        run: |
          npm i
      - name: Verify code
        run: |
          npm run verify
      - name: Create env file
        run: |
          cat << EOF > .env
          NEXT_PUBLIC_GOOGLE_ANALYTICS=${{ secrets.GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_BASE_URL=https://recipes.cortlan.dev
          EOF
      - name: Build Next.js
        run: |
          npm run build
      - name: Save build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: .next
          retention-days: 1
  deploy:
    name: Deploy
    needs: verify-code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: .next
      - name: "Google Auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - name: "Deploy to GAE"
        uses: "google-github-actions/deploy-appengine@v0"
