name: Verify
on:
  push:
    branches:
      - main
jobs:
  verify-code:
    name: Verify & Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: npm install
        run: |
          npm i
      - name: Verify code
        run: |
          npm run verify
      - name: Build Next.js
        run: |
          npm run build
      - name: 
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: out
          retention-days: 1
  Deploy:
    name: Deploy
    needs: verify-code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: out
      - name: test
        run: |
          ls -l